class DummyData {
  static const List<Map<String, dynamic>> onboardingSlides = [
    {
      'title': 'Explore Naran &\nKaghan Valley',
      'description': 'Discover the lush alpine meadows, Kunhar River, and snow covered valleys of Kaghan with intelligent guidance.',
      'query': 'Naran Kaghan valley Pakistan',
      'image': 'https://images.unsplash.com/photo-1668061867899-02b4cfa34747?q=80&w=1080&auto=format&fit=crop',
    },
    {
      'title': 'Legendary Jheel\nSaiful Malook',
      'description': 'Experience the mystical turquoise glacial lake framed by Malika Parbat peak tailored to your mood.',
      'query': 'Lake Saif ul Malook Pakistan',
      'image': 'https://images.unsplash.com/photo-1626685516371-a0ee93a0f370?q=80&w=1080&auto=format&fit=crop',
    },
    {
      'title': 'Majestic Skardu &\nShangrila Lake',
      'description': 'Journey into the heart of the Karakoram, serene cold deserts, and turquoise alpine waters with confidence.',
      'query': 'Skardu Shangrila Lake Pakistan',
      'image': 'https://images.unsplash.com/photo-1679951124125-50cc4029d727?q=80&w=1080&auto=format&fit=crop',
    },
  ];

  static const List<Map<String, dynamic>> popularDestinations = [
    {
      'id': '1',
      'name': 'Hunza Valley',
      'country': 'Pakistan',
      'rating': 4.9,
      'price': 45000,
      'duration': '5 Days',
      'distance': '600 km',
      'region': 'north',
      'latitude': 36.3167,
      'longitude': 74.6667,
      'image': 'https://images.unsplash.com/photo-1514558427911-8e293bebf18c?q=80&w=1080&auto=format&fit=crop',
      'description': 'Experience the breathtaking mountains and serene lakes of Hunza. Perfect for nature lovers and adventurers.',
      'tags': ['Mountains', 'Nature', 'Culture'],
    },
    {
      'id': '2',
      'name': 'Skardu',
      'country': 'Pakistan',
      'rating': 4.8,
      'price': 55000,
      'duration': '6 Days',
      'distance': '650 km',
      'region': 'north',
      'latitude': 35.2971,
      'longitude': 75.6333,
      'image': 'https://images.unsplash.com/photo-1679951124125-50cc4029d727?q=80&w=1080&auto=format&fit=crop',
      'description': 'Immerse yourself in the cold desert, beautiful lakes, and majestic peaks of Skardu.',
      'tags': ['Adventure', 'Nature', 'Lakes'],
    },
    {
      'id': '3',
      'name': 'Swat Valley',
      'country': 'Pakistan',
      'rating': 4.7,
      'price': 35000,
      'duration': '4 Days',
      'distance': '250 km',
      'region': 'north',
      'latitude': 35.2227,
      'longitude': 72.4258,
      'image': 'https://images.unsplash.com/photo-1668936782695-5f7657dc793d?q=80&w=1080&auto=format&fit=crop',
      'description': 'Known as the Switzerland of the East, featuring lush green forests and clear rivers.',
      'tags': ['Rivers', 'Forests', 'Relaxation'],
    },
    {
      'id': '4',
      'name': 'Fairy Meadows',
      'country': 'Pakistan',
      'rating': 4.9,
      'price': 40000,
      'duration': '5 Days',
      'distance': '450 km',
      'region': 'north',
      'latitude': 35.3853,
      'longitude': 74.5828,
      'image': 'https://images.unsplash.com/photo-1664872763520-348c1cbbade4?q=80&w=1080&auto=format&fit=crop',
      'description': 'A beautiful lush green plateau offering majestic views of Nanga Parbat.',
      'tags': ['Mountains', 'Trekking', 'Nature'],
    },
    {
      'id': '5',
      'name': 'Naran Kaghan',
      'country': 'Pakistan',
      'rating': 4.8,
      'price': 28000,
      'duration': '3 Days',
      'distance': '280 km',
      'region': 'north',
      'latitude': 34.9085,
      'longitude': 73.6528,
      'image': 'https://images.unsplash.com/photo-1668061867899-02b4cfa34747?q=80&w=1080&auto=format&fit=crop',
      'description': 'Witness the turquoise waters of Lake Saiful Malook, Kunhar River trout fishing, and Babusar Top vistas.',
      'tags': ['Valley', 'Lakes', 'Mountains'],
    },
    {
      'id': '6',
      'name': 'Kumrat Valley',
      'country': 'Pakistan',
      'rating': 4.8,
      'price': 34000,
      'duration': '4 Days',
      'distance': '370 km',
      'region': 'north',
      'latitude': 35.5414,
      'longitude': 72.2197,
      'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=1080&auto=format&fit=crop',
      'description': 'Dense pine forests, rushing Panjkora River, wooden bridges, and Jahaz Banda high alpine meadows.',
      'tags': ['Pine Forest', 'Rivers', 'Camping'],
    },
    {
      'id': '7',
      'name': 'Neelum Valley',
      'country': 'Pakistan',
      'rating': 4.9,
      'price': 38000,
      'duration': '5 Days',
      'distance': '240 km',
      'region': 'north',
      'latitude': 34.5889,
      'longitude': 73.9056,
      'image': 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1080&auto=format&fit=crop',
      'description': 'The pearl of Azad Kashmir with stops at Kutton Waterfall, Sharda Peeth ruins, and Arang Kel cable car.',
      'tags': ['Kashmir', 'Waterfalls', 'Heritage'],
    },
    {
      'id': '8',
      'name': 'Ratti Gali Lake',
      'country': 'Pakistan',
      'rating': 4.8,
      'price': 32000,
      'duration': '4 Days',
      'distance': '265 km',
      'region': 'north',
      'latitude': 34.8322,
      'longitude': 74.0583,
      'image': 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1080&auto=format&fit=crop',
      'description': 'Ascend from Dowarian via mountain jeeps to the red alpine wildflower encircled glacial lake.',
      'tags': ['Glacial Lake', 'Trekking', 'Adventure'],
    },
    {
      'id': '9',
      'name': 'Shogran & Siri Paye',
      'country': 'Pakistan',
      'rating': 4.7,
      'price': 26000,
      'duration': '3 Days',
      'distance': '225 km',
      'region': 'north',
      'latitude': 34.6300,
      'longitude': 73.4700,
      'image': 'https://images.unsplash.com/photo-1627894483216-2138af692e32?q=80&w=1080&auto=format&fit=crop',
      'description': 'Horse ride across the misty pine meadows of Siri Paye elevated 3,000 meters above Kaghan Valley.',
      'tags': ['Meadows', 'Horse Riding', 'Misty Hills'],
    },
    {
      'id': '10',
      'name': 'Kalash Valley Chitral',
      'country': 'Pakistan',
      'rating': 4.9,
      'price': 42000,
      'duration': '5 Days',
      'distance': '410 km',
      'region': 'north',
      'latitude': 35.6700,
      'longitude': 71.6800,
      'image': 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?q=80&w=1080&auto=format&fit=crop',
      'description': 'Participate in the ancient cultural traditions, folk dances, and vibrant costumes of the Kalash people.',
      'tags': ['Culture', 'Festivals', 'History'],
    },
    {
      'id': '11',
      'name': 'Deosai National Park',
      'country': 'Pakistan',
      'rating': 4.9,
      'price': 48000,
      'duration': '5 Days',
      'distance': '620 km',
      'region': 'north',
      'latitude': 35.0500,
      'longitude': 75.4500,
      'image': 'https://images.unsplash.com/photo-1426604966848-d7adac402bff?q=80&w=1080&auto=format&fit=crop',
      'description': 'The land of giants plateau home to Himalayan brown bears and heart shaped Sheosar Lake.',
      'tags': ['Plateau', 'Wildlife', 'Lakes'],
    },
    {
      'id': '12',
      'name': 'Khunjerab Pass',
      'country': 'Pakistan',
      'rating': 4.9,
      'price': 52000,
      'duration': '6 Days',
      'distance': '750 km',
      'region': 'north',
      'latitude': 36.8500,
      'longitude': 75.4300,
      'image': 'https://images.unsplash.com/photo-1426604966848-d7adac402bff?q=80&w=1080&auto=format&fit=crop',
      'description': 'Drive to the highest paved border crossing in the world at 4,693 meters elevation along the Silk Route.',
      'tags': ['Silk Road', 'High Pass', 'Border'],
    },
    {
      'id': '13',
      'name': 'Nathia Gali',
      'country': 'Pakistan',
      'rating': 4.6,
      'price': 18000,
      'duration': '2 Days',
      'distance': '85 km',
      'region': 'central',
      'latitude': 34.0700,
      'longitude': 73.3800,
      'image': 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1080&auto=format&fit=crop',
      'description': 'Trek through moist temperate pine forests to the summit of Mushkpuri with panoramic mountain views.',
      'tags': ['Forest Trails', 'Weekend Trip', 'Hiking'],
    },
    {
      'id': '14',
      'name': 'Lahore Heritage',
      'country': 'Pakistan',
      'rating': 4.7,
      'price': 22000,
      'duration': '3 Days',
      'distance': '380 km',
      'region': 'central',
      'latitude': 31.5204,
      'longitude': 74.3587,
      'image': 'https://images.unsplash.com/photo-1622546758596-f1f06ba11f58?q=80&w=1080&auto=format&fit=crop',
      'description': 'Step back in time at Badshahi Mosque, Lahore Fort, Wazir Khan Mosque, and historic Food Street.',
      'tags': ['Mughal Architecture', 'Food Trail', 'History'],
    },
    {
      'id': '15',
      'name': 'Islamabad Margalla',
      'country': 'Pakistan',
      'rating': 4.8,
      'price': 16000,
      'duration': '2 Days',
      'distance': '0 km',
      'region': 'central',
      'latitude': 33.6844,
      'longitude': 73.0479,
      'image': 'https://images.unsplash.com/photo-1608020932658-d0e19a69580b?q=80&w=1080&auto=format&fit=crop',
      'description': 'Visit the iconic Faisal Mosque, hike Margalla Trail 3, and dine above the city lights at Monal.',
      'tags': ['Capital City', 'Hiking', 'Architecture'],
    },
    {
      'id': '16',
      'name': 'Taxila Ruins',
      'country': 'Pakistan',
      'rating': 4.6,
      'price': 15000,
      'duration': '2 Days',
      'distance': '35 km',
      'region': 'central',
      'latitude': 33.7460,
      'longitude': 72.8390,
      'image': 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1080&auto=format&fit=crop',
      'description': 'UNESCO World Heritage ruins of Jaulian monastery, Dharmarajika stupa, and Gandharan civilization.',
      'tags': ['UNESCO Ruins', 'Archaeology', 'Buddhism'],
    },
    {
      'id': '17',
      'name': 'Rohtas Fort',
      'country': 'Pakistan',
      'rating': 4.7,
      'price': 19000,
      'duration': '2 Days',
      'distance': '115 km',
      'region': 'central',
      'latitude': 32.9656,
      'longitude': 73.5786,
      'image': 'https://images.unsplash.com/photo-1564507592333-c60657eea523?q=80&w=1080&auto=format&fit=crop',
      'description': 'Explore Sher Shah Suri massive 16th century military citadel and the subterranean Khewra Salt Mine.',
      'tags': ['Fortress', 'Military Heritage', 'Salt Mine'],
    },

    {
      'id': '18',
      'name': 'Cholistan Desert',
      'country': 'Pakistan',
      'rating': 4.8,
      'price': 36000,
      'duration': '4 Days',
      'distance': '620 km',
      'region': 'south',
      'latitude': 28.5000,
      'longitude': 71.8700,
      'image': 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?q=80&w=1080&auto=format&fit=crop',
      'description': 'Witness the forty towering bastions of Derawar Fort and camel safaris under a starry desert sky.',
      'tags': ['Desert Safari', 'Derawar Fort', 'Stargazing'],
    },
    {
      'id': '19',
      'name': 'Kund Malir Beach',
      'country': 'Pakistan',
      'rating': 4.8,
      'price': 24000,
      'duration': '2 Days',
      'distance': '240 km from Karachi',
      'region': 'south',
      'latitude': 25.5000,
      'longitude': 65.4500,
      'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1080&auto=format&fit=crop',
      'description': 'Cruise along Makran Coastal Highway to view the Princess of Hope, Sphinx, and pristine Arabian Sea beaches.',
      'tags': ['Golden Beach', 'Coastal Highway', 'Rock Pillars'],
    },
    {
      'id': '20',
      'name': 'Churna Island',
      'country': 'Pakistan',
      'rating': 4.7,
      'price': 18000,
      'duration': '2 Days',
      'distance': '60 km from Karachi',
      'region': 'south',
      'latitude': 24.8970,
      'longitude': 66.6080,
      'image': 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1080&auto=format&fit=crop',
      'description': 'Speedboat ride to Churna Island for cliff diving, snorkeling among coral reefs, and spotting sea turtles.',
      'tags': ['Snorkeling', 'Coral Reef', 'Water Sports'],
    },
    {
      'id': '21',
      'name': 'Gorakh Hill Station',
      'country': 'Pakistan',
      'rating': 4.6,
      'price': 25000,
      'duration': '3 Days',
      'distance': '420 km from Karachi',
      'region': 'south',
      'latitude': 26.8667,
      'longitude': 67.1500,
      'image': 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1080&auto=format&fit=crop',
      'description': 'Escape to the 5,688 feet summit of the Kirthar Mountains with zero light pollution and brisk mountain air.',
      'tags': ['Mountain Station', 'Stargazing', 'Camping'],
    },
    {
      'id': '22',
      'name': 'Ziarat Juniper Forest',
      'country': 'Pakistan',
      'rating': 4.7,
      'price': 28000,
      'duration': '3 Days',
      'distance': '125 km from Quetta',
      'region': 'south',
      'latitude': 30.3800,
      'longitude': 67.7200,
      'image': 'https://images.unsplash.com/photo-1448375240586-882707db888b?q=80&w=1080&auto=format&fit=crop',
      'description': 'One of the oldest Juniper forests on Earth and the historic wooden architecture of Quaid e Azam Residency.',
      'tags': ['Juniper Forest', 'Heritage', 'Chilly Breezes'],
    },
    {
      'id': '23',
      'name': 'Astola Island',
      'country': 'Pakistan',
      'rating': 4.9,
      'price': 58000,
      'duration': '4 Days',
      'distance': '350 km from Karachi',
      'region': 'south',
      'latitude': 25.1200,
      'longitude': 63.8500,
      'image': 'https://images.unsplash.com/photo-1518837695005-2083093ee35b?q=80&w=1080&auto=format&fit=crop',
      'description': 'Pakistan largest uninhabited island with turquoise water, sea caves, isolated shores, and coral beds.',
      'tags': ['Island Trek', 'Deep Sea', 'Turquoise Waters'],
    },
    {
      'id': '24',
      'name': 'Attabad Lake Gojal',
      'country': 'Pakistan',
      'rating': 4.9,
      'price': 39000,
      'duration': '4 Days',
      'distance': '620 km',
      'region': 'north',
      'latitude': 36.3333,
      'longitude': 74.8667,
      'image': 'https://images.unsplash.com/photo-1627894483216-2138af692e32?q=80&w=1080&auto=format&fit=crop',
      'description': 'Speedboat across turquoise alpine waters and cross the daring suspension bridges of upper Hunza.',
      'tags': ['Turquoise Lake', 'Boating', 'Bridges'],
    },
    {
      'id': '25',
      'name': 'Kalam Mahodand Lake',
      'country': 'Pakistan',
      'rating': 4.8,
      'price': 33000,
      'duration': '4 Days',
      'distance': '330 km',
      'region': 'north',
      'latitude': 35.4900,
      'longitude': 72.5800,
      'image': 'https://images.unsplash.com/photo-1668936782695-5f7657dc793d?q=80&w=1080&auto=format&fit=crop',
      'description': 'Traverse the wild Ushu pine forest and trout streams to reach the glacial jewel Mahodand Lake in upper Swat.',
      'tags': ['Swat Valley', 'Glacial Lake', 'Jeep Ride'],
    },
  ];

  static const List<Map<String, dynamic>> featuredPlaces = [
    {
      'id': 'f1',
      'name': 'Lahore',
      'country': 'Pakistan',
      'rating': 4.6,
      'price': 25000,
      'distance': '350 km',
      'region': 'central',
      'latitude': 31.5204,
      'longitude': 74.3587,
      'image': 'https://images.unsplash.com/photo-1622546758596-f1f06ba11f58?q=80&w=1080&auto=format&fit=crop',
      'description': 'The heart of Pakistan, famous for Minar e Pakistan, Badshahi Mosque, rich food, and culture.',
      'tags': ['Culture', 'Food', 'History'],
    },
    {
      'id': 'f2',
      'name': 'Islamabad',
      'country': 'Pakistan',
      'rating': 4.8,
      'price': 30000,
      'distance': '0 km',
      'region': 'central',
      'latitude': 33.6844,
      'longitude': 73.0479,
      'image': 'https://images.unsplash.com/photo-1608020932658-d0e19a69580b?q=80&w=1080&auto=format&fit=crop',
      'description': 'The capital city, featuring the iconic Faisal Mosque against the Margalla Hills.',
      'tags': ['City', 'Nature', 'Peaceful'],
    },
    {
      'id': 'f3',
      'name': 'Naran',
      'country': 'Pakistan',
      'rating': 4.7,
      'price': 40000,
      'distance': '280 km',
      'region': 'central',
      'latitude': 34.9085,
      'longitude': 73.6528,
      'image': 'https://images.unsplash.com/photo-1668061867899-02b4cfa34747?q=80&w=1080&auto=format&fit=crop',
      'description': 'A beautiful valley surrounded by lush green mountains and gateway to Saiful Malook Lake.',
      'tags': ['Valley', 'Nature', 'River'],
    },
    {
      'id': 'f4',
      'name': 'Kund Malir',
      'country': 'Pakistan',
      'rating': 4.8,
      'price': 24000,
      'distance': '240 km',
      'region': 'south',
      'latitude': 25.5000,
      'longitude': 65.4500,
      'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1080&auto=format&fit=crop',
      'description': 'Pristine golden beach on the Arabian Sea framed by the desert mountains of Hingol.',
      'tags': ['Beach', 'Balochistan', 'Coastal'],
    },
    {
      'id': 'f5',
      'name': 'Kumrat Valley',
      'country': 'Pakistan',
      'rating': 4.8,
      'price': 34000,
      'distance': '370 km',
      'region': 'north',
      'latitude': 35.5414,
      'longitude': 72.2197,
      'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=1080&auto=format&fit=crop',
      'description': 'Alpine river streams and virgin deodar pine forests in Khyber Pakhtunkhwa.',
      'tags': ['Pine Trees', 'Rivers', 'Hiking'],
    },
  ];


  static const List<Map<String, dynamic>> chatMessages = [
    {
      'isMe': false,
      'text': 'Hi! I am your AI Travel Assistant. Where would you like to go?',
      'time': '10:00 AM',
    },
    {
      'isMe': true,
      'text': 'I am looking for a relaxing mountain vacation.',
      'time': '10:01 AM',
    },
    {
      'isMe': false,
      'text': 'Great! A scenic mountain getaway. Here are a few top recommendations for you:',
      'time': '10:02 AM',
      'destination_card': true, 
    },
    {
      'isMe': true,
      'text': 'Swat looks amazing! What is the estimated budget?',
      'time': '10:05 AM',
    },
    {
      'isMe': false,
      'text': 'For a 5 day trip to Swat for two, including travel, accommodation, and food, you are looking at approximately PKR 75,000.',
      'time': '10:06 AM',
    },
  ];

  static const List<Map<String, dynamic>> routeOptions = [
    {
      'id': 'fast',
      'title': 'Fastest Route (KKH Highway)',
      'duration': '11h 30m',
      'distance': '580 km',
      'stops': 1,
      'price': 'PKR 12,000',
      'type': 'fast',
      'tag': 'Fastest Path',
      'color': 0xFF0D9488,
    },
    {
      'id': 'scenic',
      'title': 'Scenic Route (Naran & Babusar Pass)',
      'duration': '14h 45m',
      'distance': '640 km',
      'stops': 5,
      'price': 'PKR 16,500',
      'type': 'scenic',
      'tag': 'Scenic Mountain Corridor',
      'color': 0xFFF59E0B,
    },
  ];

  static const List<Map<String, dynamic>> routeAttractions = [
    {
      'id': 'att_1',
      'name': 'Kallar Kahar Salt Lake',
      'category': 'Salt Lake & Garden',
      'latitude': 32.7819,
      'longitude': 72.7056,
      'description': 'Natural saltwater lake surrounded by peacock orchards and historic Takht e Babri.',
      'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
      'rating': 4.6,
      'distance': '125 km from Islamabad',
      'corridor': 'M2 Motorway (Islamabad to Lahore)',
      'accessibility': 'Direct Road Access',
      'travelTip': 'Paved motorway interchange exit. Family boating and lakeside picnic spots available.',
    },
    {
      'id': 'att_2',
      'name': 'Katas Raj Historic Temples',
      'category': 'Historic Heritage',
      'latitude': 32.7247,
      'longitude': 72.9547,
      'description': 'Ancient Hindu temple complex surrounding a sacred pond connected by Shiva legend.',
      'image': 'https://images.unsplash.com/photo-1590059390046-65a4fa4347fc?auto=format&fit=crop&w=800&q=80',
      'rating': 4.7,
      'distance': '145 km from Islamabad',
      'corridor': 'M2 Motorway (Islamabad to Lahore)',
      'accessibility': 'Direct Road Access',
      'travelTip': 'Accessible via Choa Saidan Shah road. Guided tours available inside temple grounds.',
    },
    {
      'id': 'att_3',
      'name': 'Khewra Salt Mine & Crystal Palace',
      'category': 'Mineral Cavern',
      'latitude': 32.6500,
      'longitude': 73.0100,
      'description': 'World second largest salt mine with illuminated crystal salt mosques and bridges.',
      'image': 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
      'rating': 4.8,
      'distance': '160 km from Islamabad',
      'corridor': 'M2 Motorway (Islamabad to Lahore)',
      'accessibility': 'Direct Road Access',
      'travelTip': 'Miniature electric train rides into mine chambers. Light jacket recommended inside.',
    },
    {
      'id': 'att_4',
      'name': 'Rohtas Fort Citadel',
      'category': 'UNESCO Fortress',
      'latitude': 32.9667,
      'longitude': 73.5833,
      'description': 'Grand 16th century fortress built by Sher Shah Suri with massive stone bastions.',
      'image': 'https://images.unsplash.com/photo-1599837565318-67429bde7162?auto=format&fit=crop&w=800&q=80',
      'rating': 4.8,
      'distance': '110 km from Islamabad',
      'corridor': 'GT Road & M2 (Islamabad to Lahore)',
      'accessibility': 'Direct Road Access',
      'travelTip': 'Paved road up to Sohail Gate. Wear comfortable walking shoes for rampart walks.',
    },
    {
      'id': 'att_5',
      'name': 'Hiran Minar Water Pavilion',
      'category': 'Mughal Heritage',
      'latitude': 31.7456,
      'longitude': 73.9536,
      'description': 'Scenic royal hunting pavilion and grand water tank built by Emperor Jahangir.',
      'image': 'https://images.unsplash.com/photo-1587974928442-77dc3e0dba72?auto=format&fit=crop&w=800&q=80',
      'rating': 4.6,
      'distance': '45 km from Lahore',
      'corridor': 'M2 Motorway (Islamabad to Lahore)',
      'accessibility': 'Direct Road Access',
      'travelTip': 'Close to Sheikhupura interchange. Excellent stop for sunset photography.',
    },
    {
      'id': 'att_6',
      'name': 'Saiful Malook Glacial Lake',
      'category': 'Alpine Glacial Lake',
      'latitude': 34.8767,
      'longitude': 73.6931,
      'description': 'Legendary turquoise lake at 3,224 meters framed by snow covered Malika Parbat peak.',
      'image': 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
      'rating': 4.9,
      'distance': '285 km from Islamabad',
      'corridor': 'Naran & Babusar Pass (North Route)',
      'accessibility': '4x4 Jeep Required',
      'travelTip': 'Hire a local 4x4 jeep from Naran bazaar (30 min ascent). Pack warm clothing.',
    },
    {
      'id': 'att_7',
      'name': 'Babusar Top Pass',
      'category': 'High Mountain Pass',
      'latitude': 35.1481,
      'longitude': 74.0483,
      'description': 'Breathtaking 4,173 meter high pass connecting Kaghan Valley with Gilgit Baltistan.',
      'image': 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
      'rating': 4.9,
      'distance': '360 km from Islamabad',
      'corridor': 'Naran & Babusar Pass (North Route)',
      'accessibility': 'Direct Road Access',
      'travelTip': 'Paved national highway open June to October. Cold wind gusts, bring winter coats.',
    },
    {
      'id': 'att_8',
      'name': 'Lulusar Lake & Dudipatsar Runoff',
      'category': 'Cascade Lake',
      'latitude': 35.0833,
      'longitude': 73.9167,
      'description': 'Pristine high altitude lake serving as the main source of the roaring Kunhar River.',
      'image': 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=800&q=80',
      'rating': 4.7,
      'distance': '330 km from Islamabad',
      'corridor': 'Naran & Babusar Pass (North Route)',
      'accessibility': 'Direct Road Access',
      'travelTip': 'Roadside parking right on Babusar highway. Excellent panorama for road trips.',
    },
    {
      'id': 'att_9',
      'name': 'Attabad Lake & Tunnel Drive',
      'category': 'Turquoise Lake',
      'latitude': 36.3333,
      'longitude': 74.8667,
      'description': 'Vibrant turquoise waters formed along Karakoram Highway with water boat safaris.',
      'image': 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=80',
      'rating': 4.9,
      'distance': '600 km from Islamabad',
      'corridor': 'Karakoram Highway (Gilgit to Hunza)',
      'accessibility': 'Direct Road Access',
      'travelTip': 'Smooth Karakoram Highway drive through modern tunnels. Jet ski and boating points.',
    },
    {
      'id': 'att_10',
      'name': 'Altit & Baltit Royal Forts',
      'category': 'Historic Heritage',
      'latitude': 36.3139,
      'longitude': 74.6714,
      'description': 'Ancient fortified castles commanding supreme vistas over Hunza Valley and Rakaposhi.',
      'image': 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
      'rating': 4.9,
      'distance': '580 km from Islamabad',
      'corridor': 'Hunza Valley (North Route)',
      'accessibility': 'Moderate Walk Required',
      'travelTip': '15 minute walking trail up historical Karimabad village. Guided heritage tours.',
    },
    {
      'id': 'att_11',
      'name': 'Malam Jabba Ski Resort',
      'category': 'Alpine Ski & Chairlift',
      'latitude': 34.7994,
      'longitude': 72.5714,
      'description': 'Scenic hill station in Swat Valley with mountain chairlift, zip line, and pine views.',
      'image': 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
      'rating': 4.8,
      'distance': '290 km from Islamabad',
      'corridor': 'Swat Expressway & Mingora (North Route)',
      'accessibility': 'Direct Road Access',
      'travelTip': 'Paved hill highway from Mingora. Snow in winter and cool pine breeze in summer.',
    },
    {
      'id': 'att_12',
      'name': 'Harappa Ancient Bronze Age Site',
      'category': '5,000 Year Indus Ruins',
      'latitude': 30.6300,
      'longitude': 72.8647,
      'description': 'Cradle of Indus Valley Civilization featuring ancient town planning, wells, and museum.',
      'image': 'https://images.unsplash.com/photo-1590059390046-65a4fa4347fc?auto=format&fit=crop&w=800&q=80',
      'rating': 4.6,
      'distance': '180 km from Lahore',
      'corridor': 'National Highway N5 (Lahore to Multan)',
      'accessibility': 'Direct Road Access',
      'travelTip': 'Accessible from Sahiwal. On site archaeological museum open daily.',
    },
    {
      'id': 'att_13',
      'name': 'Shah Rukn e Alam Grand Mausoleum',
      'category': 'Sufi Heritage',
      'latitude': 30.1983,
      'longitude': 71.4722,
      'description': 'Towering octagonal landmark of Tughluq architecture adorned with Kashigari tiles.',
      'image': 'https://images.unsplash.com/photo-1587974928442-77dc3e0dba72?auto=format&fit=crop&w=800&q=80',
      'rating': 4.8,
      'distance': 'Multan City Center',
      'corridor': 'M4 & M5 Motorways (Multan & South)',
      'accessibility': 'Direct Road Access',
      'travelTip': 'Located atop the ancient Multan Fort mound with panoramic city views.',
    },
    {
      'id': 'att_14',
      'name': 'Derawar Fort & Desert Dunes',
      'category': 'Desert Fortress',
      'latitude': 28.7672,
      'longitude': 71.3342,
      'description': 'Colossal square fortress with 40 round bastions rising dramatically over Cholistan.',
      'image': 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=800&q=80',
      'rating': 4.9,
      'distance': '95 km from Bahawalpur',
      'corridor': 'M5 Motorway Corridor (South Punjab)',
      'accessibility': '4x4 or Paved Desert Road',
      'travelTip': 'Best visited during late afternoon for sunset camel safari over golden sand dunes.',
    },
    {
      'id': 'att_15',
      'name': 'Keenjhar Lake Resort',
      'category': 'Freshwater Lake',
      'latitude': 24.9667,
      'longitude': 68.0500,
      'description': 'Expansive blue lake steeped in the folklore of Noori Jam Tamachi with motorboat safaris.',
      'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
      'rating': 4.5,
      'distance': '120 km from Karachi',
      'corridor': 'National Highway N5 (Karachi to Hyderabad)',
      'accessibility': 'Direct Road Access',
      'travelTip': 'Paved national highway exit at Thatta. Motorboat rides to island shrine available.',
    },
    {
      'id': 'att_16',
      'name': 'Makli UNESCO Necropolis',
      'category': 'Ancient Royal Tombs',
      'latitude': 24.7500,
      'longitude': 67.9000,
      'description': 'Sprawling necropolis with elaborate carved sandstone tombs of kings, queens, and saints.',
      'image': 'https://images.unsplash.com/photo-1599837565318-67429bde7162?auto=format&fit=crop&w=800&q=80',
      'rating': 4.7,
      'distance': '98 km from Karachi',
      'corridor': 'National Highway N5 (Karachi to Hyderabad)',
      'accessibility': 'Direct Road Access',
      'travelTip': 'Electric golf carts available for touring the sprawling historical grounds.',
    },
  ];

  static const List<String> moods = [
    'Relaxing', 'Adventurous', 'Romantic', 'Cultural', 'Nature', 'Historical'
  ];
}
