class DummyData {
  static const List<Map<String, dynamic>> onboardingSlides = [
    {
      'title': 'Explore Naran &\nKaghan Valley',
      'description': 'Discover the lush alpine meadows, Kunhar River, and snow-draped valleys of Kaghan with intelligent guidance.',
      'query': 'Naran Kaghan valley Pakistan',
      'image': 'https://images.unsplash.com/photo-1668061867899-02b4cfa34747?q=80&w=1080&auto=format&fit=crop',
    },
    {
      'title': 'Legendary Jheel\nSaiful Malook',
      'description': 'Experience the mystical turquoise glacial lake framed by Malika Parbat peak tailored to your mood.',
      'query': 'Lake Saif ul Malook Pakistan',
      'image': 'https://images.unsplash.com/photo-1626685516371-a0ee93a0f370?q=80&w=1080&auto=format&fit=crop',
    },
    {
      'title': 'Majestic Skardu &\nShangrila Lake',
      'description': 'Journey into the heart of the Karakoram, serene cold deserts, and turquoise alpine waters with confidence.',
      'query': 'Skardu Shangrila Lake Pakistan',
      'image': 'https://images.unsplash.com/photo-1679951124125-50cc4029d727?q=80&w=1080&auto=format&fit=crop',
    },
  ];

  static const List<Map<String, dynamic>> popularDestinations = [
    {
      'id': '1',
      'name': 'Hunza Valley',
      'country': 'Pakistan',
      'rating': 4.9,
      'price': 45000,
      'distance': '600 km',
      'region': 'north',
      'latitude': 36.3167,
      'longitude': 74.6667,
      'image': 'https://images.unsplash.com/photo-1514558427911-8e293bebf18c?q=80&w=1080&auto=format&fit=crop',
      'description': 'Experience the breathtaking mountains and serene lakes of Hunza. Perfect for nature lovers and adventurers.',
      'tags': ['Mountains', 'Nature', 'Culture'],
    },
    {
      'id': '2',
      'name': 'Skardu',
      'country': 'Pakistan',
      'rating': 4.8,
      'price': 55000,
      'distance': '650 km',
      'region': 'north',
      'latitude': 35.2971,
      'longitude': 75.6333,
      'image': 'https://images.unsplash.com/photo-1679951124125-50cc4029d727?q=80&w=1080&auto=format&fit=crop',
      'description': 'Immerse yourself in the cold desert, beautiful lakes, and majestic peaks of Skardu.',
      'tags': ['Adventure', 'Nature', 'Lakes'],
    },
    {
      'id': '3',
      'name': 'Swat Valley',
      'country': 'Pakistan',
      'rating': 4.7,
      'price': 35000,
      'distance': '250 km',
      'region': 'north',
      'latitude': 35.2227,
      'longitude': 72.4258,
      'image': 'https://images.unsplash.com/photo-1668936782695-5f7657dc793d?q=80&w=1080&auto=format&fit=crop',
      'description': 'Known as the Switzerland of the East, featuring lush green forests and clear rivers.',
      'tags': ['Rivers', 'Forests', 'Relaxation'],
    },
    {
      'id': '4',
      'name': 'Fairy Meadows',
      'country': 'Pakistan',
      'rating': 4.9,
      'price': 40000,
      'distance': '450 km',
      'region': 'north',
      'latitude': 35.3853,
      'longitude': 74.5828,
      'image': 'https://images.unsplash.com/photo-1664872763520-348c1cbbade4?q=80&w=1080&auto=format&fit=crop',
      'description': 'A beautiful lush green plateau offering majestic views of Nanga Parbat.',
      'tags': ['Mountains', 'Trekking', 'Nature'],
    },
  ];

  static const List<Map<String, dynamic>> featuredPlaces = [
    {
      'id': 'f1',
      'name': 'Lahore',
      'country': 'Pakistan',
      'rating': 4.6,
      'price': 25000,
      'distance': '350 km',
      'region': 'central',
      'latitude': 31.5204,
      'longitude': 74.3587,
      'image': 'https://images.unsplash.com/photo-1622546758596-f1f06ba11f58?q=80&w=1080&auto=format&fit=crop',
      'description': 'The heart of Pakistan, famous for Minar-e-Pakistan, Badshahi Mosque, rich food, and culture.',
      'tags': ['Culture', 'Food', 'History'],
    },
    {
      'id': 'f2',
      'name': 'Islamabad',
      'country': 'Pakistan',
      'rating': 4.8,
      'price': 30000,
      'distance': '0 km',
      'region': 'central',
      'latitude': 33.6844,
      'longitude': 73.0479,
      'image': 'https://images.unsplash.com/photo-1608020932658-d0e19a69580b?q=80&w=1080&auto=format&fit=crop',
      'description': 'The capital city, featuring the iconic Faisal Mosque against the Margalla Hills.',
      'tags': ['City', 'Nature', 'Peaceful'],
    },
    {
      'id': 'f3',
      'name': 'Naran',
      'country': 'Pakistan',
      'rating': 4.7,
      'price': 40000,
      'distance': '280 km',
      'region': 'central',
      'latitude': 34.9085,
      'longitude': 73.6528,
      'image': 'https://images.unsplash.com/photo-1668061867899-02b4cfa34747?q=80&w=1080&auto=format&fit=crop',
      'description': 'A beautiful valley surrounded by lush green mountains and gateway to Saif-ul-Malook Lake.',
      'tags': ['Valley', 'Nature', 'River'],
    },
  ];

  static const List<Map<String, dynamic>> chatMessages = [
    {
      'isMe': false,
      'text': 'Hi! I am your AI Travel Assistant. Where would you like to go?',
      'time': '10:00 AM',
    },
    {
      'isMe': true,
      'text': 'I am looking for a relaxing mountain vacation.',
      'time': '10:01 AM',
    },
    {
      'isMe': false,
      'text': 'Great! A scenic mountain getaway. Here are a few top recommendations for you:',
      'time': '10:02 AM',
      'destination_card': true, 
    },
    {
      'isMe': true,
      'text': 'Swat looks amazing! What is the estimated budget?',
      'time': '10:05 AM',
    },
    {
      'isMe': false,
      'text': 'For a 5-day trip to Swat for two, including travel, accommodation, and food, you are looking at approximately PKR 75,000.',
      'time': '10:06 AM',
    },
  ];

  static const List<Map<String, dynamic>> routeOptions = [
    {
      'id': 'fast',
      'title': 'Fastest Route (KKH Highway)',
      'duration': '11h 30m',
      'distance': '580 km',
      'stops': 1,
      'price': 'PKR 12,000',
      'type': 'fast',
      'tag': 'Fastest Path',
      'color': 0xFF0D9488,
    },
    {
      'id': 'scenic',
      'title': 'Scenic Route (Naran & Babusar Pass)',
      'duration': '14h 45m',
      'distance': '640 km',
      'stops': 5,
      'price': 'PKR 16,500',
      'type': 'scenic',
      'tag': 'Scenic Mountain Corridor',
      'color': 0xFFF59E0B,
    },
  ];

  static const List<Map<String, dynamic>> routeAttractions = [
    {
      'id': 'att_1',
      'name': 'Kallar Kahar Lake',
      'category': 'Lake',
      'latitude': 32.7819,
      'longitude': 72.7056,
      'description': 'Salt lake with natural gardens, historical Takht-e-Babri, and peacocks.',
      'image': 'https://images.unsplash.com/photo-1630139266136-1e663a0a322e?q=80&w=2074&auto=format&fit=crop',
      'rating': 4.5,
      'distance': '125 km from Islamabad',
    },
    {
      'id': 'att_2',
      'name': 'Saif-ul-Malook Lake',
      'category': 'Lake',
      'latitude': 34.8767,
      'longitude': 73.6931,
      'description': 'Legendary glacial lake surrounded by snow-draped Malika Parbat peak.',
      'image': 'https://images.unsplash.com/photo-1581895690858-a5ea6c4d7e00?q=80&w=2070&auto=format&fit=crop',
      'rating': 4.9,
      'distance': '285 km from Islamabad',
    },
    {
      'id': 'att_3',
      'name': 'Babusar Top Pass',
      'category': 'Mountain Pass',
      'latitude': 35.1481,
      'longitude': 74.0483,
      'description': 'High mountain pass at 4,173 meters with panoramic Himalayan and Karakoram vistas.',
      'image': 'https://images.unsplash.com/photo-1595166249673-c62d0943eb14?q=80&w=2070&auto=format&fit=crop',
      'rating': 4.8,
      'distance': '360 km from Islamabad',
    },
    {
      'id': 'att_4',
      'name': 'Lulusar Lake & Waterfall',
      'category': 'Waterfall & Lake',
      'latitude': 35.0833,
      'longitude': 73.9167,
      'description': 'Pristine mountain lake with cascading alpine runoff waterfalls.',
      'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=2070&auto=format&fit=crop',
      'rating': 4.7,
      'distance': '330 km from Islamabad',
    },
    {
      'id': 'att_5',
      'name': 'Altit Fort & Royal Garden',
      'category': 'Historic Heritage',
      'latitude': 36.3139,
      'longitude': 74.6714,
      'description': 'Ancient 900-year-old fort perched above the Hunza River canyon.',
      'image': 'https://images.unsplash.com/photo-1631558288597-28d8ed273fec?q=80&w=2070&auto=format&fit=crop',
      'rating': 4.9,
      'distance': 'Destination Landmark',
    },
    {
      'id': 'att_6',
      'name': 'Attabad Lake & Tunnel',
      'category': 'Scenic Landmark',
      'latitude': 36.3333,
      'longitude': 74.8667,
      'description': 'World-famous turquoise blue lake formed along the Karakoram Highway.',
      'image': 'https://images.unsplash.com/photo-1627894483216-2138af692e32?q=80&w=2070&auto=format&fit=crop',
      'rating': 4.9,
      'distance': '20 km past Hunza',
    },
  ];

  static const List<String> moods = [
    'Relaxing', 'Adventurous', 'Romantic', 'Cultural', 'Nature', 'Historical'
  ];
}
