class DummyData {
  static const List<Map<String, dynamic>> onboardingSlides = [
    {
      'title': 'Explore Naran &\nKaghan Valley',
      'description': 'Discover the lush alpine meadows, Kunhar River, and snow-draped valleys of Kaghan with intelligent guidance.',
      'query': 'Naran Kaghan valley Pakistan',
      'image': 'https://images.unsplash.com/photo-1668061867899-02b4cfa34747?q=80&w=1080&auto=format&fit=crop',
    },
    {
      'title': 'Legendary Jheel\nSaiful Malook',
      'description': 'Experience the mystical turquoise glacial lake framed by Malika Parbat peak tailored to your mood.',
      'query': 'Lake Saif ul Malook Pakistan',
      'image': 'https://images.unsplash.com/photo-1626685516371-a0ee93a0f370?q=80&w=1080&auto=format&fit=crop',
    },
    {
      'title': 'Majestic Skardu &\nShangrila Lake',
      'description': 'Journey into the heart of the Karakoram, serene cold deserts, and turquoise alpine waters with confidence.',
      'query': 'Skardu Shangrila Lake Pakistan',
      'image': 'https://images.unsplash.com/photo-1679951124125-50cc4029d727?q=80&w=1080&auto=format&fit=crop',
    },
  ];

  static const List<Map<String, dynamic>> popularDestinations = [
    {
      'id': '1',
      'name': 'Hunza Valley',
      'country': 'Pakistan',
      'rating': 4.9,
      'price': 45000,
      'duration': '5 Days',
      'distance': '600 km',
      'region': 'north',
      'latitude': 36.3167,
      'longitude': 74.6667,
      'image': 'https://images.unsplash.com/photo-1514558427911-8e293bebf18c?q=80&w=1080&auto=format&fit=crop',
      'description': 'Experience the breathtaking mountains and serene lakes of Hunza. Perfect for nature lovers and adventurers.',
      'tags': ['Mountains', 'Nature', 'Culture'],
    },
    {
      'id': '2',
      'name': 'Skardu',
      'country': 'Pakistan',
      'rating': 4.8,
      'price': 55000,
      'duration': '6 Days',
      'distance': '650 km',
      'region': 'north',
      'latitude': 35.2971,
      'longitude': 75.6333,
      'image': 'https://images.unsplash.com/photo-1679951124125-50cc4029d727?q=80&w=1080&auto=format&fit=crop',
      'description': 'Immerse yourself in the cold desert, beautiful lakes, and majestic peaks of Skardu.',
      'tags': ['Adventure', 'Nature', 'Lakes'],
    },
    {
      'id': '3',
      'name': 'Swat Valley',
      'country': 'Pakistan',
      'rating': 4.7,
      'price': 35000,
      'duration': '4 Days',
      'distance': '250 km',
      'region': 'north',
      'latitude': 35.2227,
      'longitude': 72.4258,
      'image': 'https://images.unsplash.com/photo-1668936782695-5f7657dc793d?q=80&w=1080&auto=format&fit=crop',
      'description': 'Known as the Switzerland of the East, featuring lush green forests and clear rivers.',
      'tags': ['Rivers', 'Forests', 'Relaxation'],
    },
    {
      'id': '4',
      'name': 'Fairy Meadows',
      'country': 'Pakistan',
      'rating': 4.9,
      'price': 40000,
      'duration': '5 Days',
      'distance': '450 km',
      'region': 'north',
      'latitude': 35.3853,
      'longitude': 74.5828,
      'image': 'https://images.unsplash.com/photo-1664872763520-348c1cbbade4?q=80&w=1080&auto=format&fit=crop',
      'description': 'A beautiful lush green plateau offering majestic views of Nanga Parbat.',
      'tags': ['Mountains', 'Trekking', 'Nature'],
    },
    {
      'id': '5',
      'name': 'Naran Kaghan',
      'country': 'Pakistan',
      'rating': 4.8,
      'price': 28000,
      'duration': '3 Days',
      'distance': '280 km',
      'region': 'north',
      'latitude': 34.9085,
      'longitude': 73.6528,
      'image': 'https://images.unsplash.com/photo-1668061867899-02b4cfa34747?q=80&w=1080&auto=format&fit=crop',
      'description': 'Witness the turquoise waters of Lake Saiful Malook, Kunhar River trout fishing, and Babusar Top vistas.',
      'tags': ['Valley', 'Lakes', 'Mountains'],
    },
    {
      'id': '6',
      'name': 'Kumrat Valley',
      'country': 'Pakistan',
      'rating': 4.8,
      'price': 34000,
      'duration': '4 Days',
      'distance': '370 km',
      'region': 'north',
      'latitude': 35.5414,
      'longitude': 72.2197,
      'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=1080&auto=format&fit=crop',
      'description': 'Dense pine forests, rushing Panjkora River, wooden bridges, and Jahaz Banda high alpine meadows.',
      'tags': ['Pine Forest', 'Rivers', 'Camping'],
    },
    {
      'id': '7',
      'name': 'Neelum Valley',
      'country': 'Pakistan',
      'rating': 4.9,
      'price': 38000,
      'duration': '5 Days',
      'distance': '240 km',
      'region': 'north',
      'latitude': 34.5889,
      'longitude': 73.9056,
      'image': 'https://images.unsplash.com/photo-1581895690858-a5ea6c4d7e00?q=80&w=1080&auto=format&fit=crop',
      'description': 'The pearl of Azad Kashmir with stops at Kutton Waterfall, Sharda Peeth ruins, and Arang Kel cable car.',
      'tags': ['Kashmir', 'Waterfalls', 'Heritage'],
    },
    {
      'id': '8',
      'name': 'Ratti Gali Lake',
      'country': 'Pakistan',
      'rating': 4.8,
      'price': 32000,
      'duration': '4 Days',
      'distance': '265 km',
      'region': 'north',
      'latitude': 34.8322,
      'longitude': 74.0583,
      'image': 'https://images.unsplash.com/photo-1595166249673-c62d0943eb14?q=80&w=1080&auto=format&fit=crop',
      'description': 'Ascend from Dowarian via mountain jeeps to the red alpine wildflower encircled glacial lake.',
      'tags': ['Glacial Lake', 'Trekking', 'Adventure'],
    },
    {
      'id': '9',
      'name': 'Shogran & Siri Paye',
      'country': 'Pakistan',
      'rating': 4.7,
      'price': 26000,
      'duration': '3 Days',
      'distance': '225 km',
      'region': 'north',
      'latitude': 34.6300,
      'longitude': 73.4700,
      'image': 'https://images.unsplash.com/photo-1627894483216-2138af692e32?q=80&w=1080&auto=format&fit=crop',
      'description': 'Horse ride across the misty pine meadows of Siri Paye elevated 3,000 meters above Kaghan Valley.',
      'tags': ['Meadows', 'Horse Riding', 'Misty Hills'],
    },
    {
      'id': '10',
      'name': 'Kalash Valley Chitral',
      'country': 'Pakistan',
      'rating': 4.9,
      'price': 42000,
      'duration': '5 Days',
      'distance': '410 km',
      'region': 'north',
      'latitude': 35.6700,
      'longitude': 71.6800,
      'image': 'https://images.unsplash.com/photo-1596761224566-32454a8549e3?q=80&w=1080&auto=format&fit=crop',
      'description': 'Participate in the ancient cultural traditions, folk dances, and vibrant costumes of the Kalash people.',
      'tags': ['Culture', 'Festivals', 'History'],
    },
    {
      'id': '11',
      'name': 'Deosai National Park',
      'country': 'Pakistan',
      'rating': 4.9,
      'price': 48000,
      'duration': '5 Days',
      'distance': '620 km',
      'region': 'north',
      'latitude': 35.0500,
      'longitude': 75.4500,
      'image': 'https://images.unsplash.com/photo-1631558288597-28d8ed273fec?q=80&w=1080&auto=format&fit=crop',
      'description': 'The land of giants plateau home to Himalayan brown bears and heart shaped Sheosar Lake.',
      'tags': ['Plateau', 'Wildlife', 'Lakes'],
    },
    {
      'id': '12',
      'name': 'Khunjerab Pass',
      'country': 'Pakistan',
      'rating': 4.9,
      'price': 52000,
      'duration': '6 Days',
      'distance': '750 km',
      'region': 'north',
      'latitude': 36.8500,
      'longitude': 75.4300,
      'image': 'https://images.unsplash.com/photo-1601633596700-0834ba128564?q=80&w=1080&auto=format&fit=crop',
      'description': 'Drive to the highest paved border crossing in the world at 4,693 meters elevation along the Silk Route.',
      'tags': ['Silk Road', 'High Pass', 'Border'],
    },
    {
      'id': '13',
      'name': 'Nathia Gali',
      'country': 'Pakistan',
      'rating': 4.6,
      'price': 18000,
      'duration': '2 Days',
      'distance': '85 km',
      'region': 'central',
      'latitude': 34.0700,
      'longitude': 73.3800,
      'image': 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?q=80&w=1080&auto=format&fit=crop',
      'description': 'Trek through moist temperate pine forests to the summit of Mushkpuri with panoramic mountain views.',
      'tags': ['Forest Trails', 'Weekend Trip', 'Hiking'],
    },
    {
      'id': '14',
      'name': 'Lahore Heritage',
      'country': 'Pakistan',
      'rating': 4.7,
      'price': 22000,
      'duration': '3 Days',
      'distance': '380 km',
      'region': 'central',
      'latitude': 31.5204,
      'longitude': 74.3587,
      'image': 'https://images.unsplash.com/photo-1622546758596-f1f06ba11f58?q=80&w=1080&auto=format&fit=crop',
      'description': 'Step back in time at Badshahi Mosque, Lahore Fort, Wazir Khan Mosque, and historic Food Street.',
      'tags': ['Mughal Architecture', 'Food Trail', 'History'],
    },
    {
      'id': '15',
      'name': 'Islamabad Margalla',
      'country': 'Pakistan',
      'rating': 4.8,
      'price': 16000,
      'duration': '2 Days',
      'distance': '0 km',
      'region': 'central',
      'latitude': 33.6844,
      'longitude': 73.0479,
      'image': 'https://images.unsplash.com/photo-1608020932658-d0e19a69580b?q=80&w=1080&auto=format&fit=crop',
      'description': 'Visit the iconic Faisal Mosque, hike Margalla Trail 3, and dine above the city lights at Monal.',
      'tags': ['Capital City', 'Hiking', 'Architecture'],
    },
    {
      'id': '16',
      'name': 'Taxila Ruins',
      'country': 'Pakistan',
      'rating': 4.6,
      'price': 15000,
      'duration': '2 Days',
      'distance': '35 km',
      'region': 'central',
      'latitude': 33.7460,
      'longitude': 72.8390,
      'image': 'https://images.unsplash.com/photo-1599818818817-2384f50bb00d?q=80&w=1080&auto=format&fit=crop',
      'description': 'UNESCO World Heritage ruins of Jaulian monastery, Dharmarajika stupa, and Gandharan civilization.',
      'tags': ['UNESCO Ruins', 'Archaeology', 'Buddhism'],
    },
    {
      'id': '17',
      'name': 'Rohtas Fort',
      'country': 'Pakistan',
      'rating': 4.7,
      'price': 19000,
      'duration': '2 Days',
      'distance': '115 km',
      'region': 'central',
      'latitude': 32.9656,
      'longitude': 73.5786,
      'image': 'https://images.unsplash.com/photo-1585255318859-f5c15f4cffa9?q=80&w=1080&auto=format&fit=crop',
      'description': 'Explore Sher Shah Suri massive 16th century military citadel and the subterranean Khewra Salt Mine.',
      'tags': ['Fortress', 'Military Heritage', 'Salt Mine'],
    },
    {
      'id': '18',
      'name': 'Cholistan Desert',
      'country': 'Pakistan',
      'rating': 4.8,
      'price': 36000,
      'duration': '4 Days',
      'distance': '620 km',
      'region': 'south',
      'latitude': 28.5000,
      'longitude': 71.8700,
      'image': 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?q=80&w=1080&auto=format&fit=crop',
      'description': 'Witness the forty towering bastions of Derawar Fort and camel safaris under a starry desert sky.',
      'tags': ['Desert Safari', 'Derawar Fort', 'Stargazing'],
    },
    {
      'id': '19',
      'name': 'Kund Malir Beach',
      'country': 'Pakistan',
      'rating': 4.8,
      'price': 24000,
      'duration': '2 Days',
      'distance': '240 km from Karachi',
      'region': 'south',
      'latitude': 25.5000,
      'longitude': 65.4500,
      'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1080&auto=format&fit=crop',
      'description': 'Cruise along Makran Coastal Highway to view the Princess of Hope, Sphinx, and pristine Arabian Sea beaches.',
      'tags': ['Golden Beach', 'Coastal Highway', 'Rock Pillars'],
    },
    {
      'id': '20',
      'name': 'Churna Island',
      'country': 'Pakistan',
      'rating': 4.7,
      'price': 18000,
      'duration': '2 Days',
      'distance': '60 km from Karachi',
      'region': 'south',
      'latitude': 24.8970,
      'longitude': 66.6080,
      'image': 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1080&auto=format&fit=crop',
      'description': 'Speedboat ride to Churna Island for cliff diving, snorkeling among coral reefs, and spotting sea turtles.',
      'tags': ['Snorkeling', 'Coral Reef', 'Water Sports'],
    },
    {
      'id': '21',
      'name': 'Gorakh Hill Station',
      'country': 'Pakistan',
      'rating': 4.6,
      'price': 25000,
      'duration': '3 Days',
      'distance': '420 km from Karachi',
      'region': 'south',
      'latitude': 26.8667,
      'longitude': 67.1500,
      'image': 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1080&auto=format&fit=crop',
      'description': 'Escape to the 5,688 feet summit of the Kirthar Mountains with zero light pollution and brisk mountain air.',
      'tags': ['Mountain Station', 'Stargazing', 'Camping'],
    },
    {
      'id': '22',
      'name': 'Ziarat Juniper Forest',
      'country': 'Pakistan',
      'rating': 4.7,
      'price': 28000,
      'duration': '3 Days',
      'distance': '125 km from Quetta',
      'region': 'south',
      'latitude': 30.3800,
      'longitude': 67.7200,
      'image': 'https://images.unsplash.com/photo-1448375240586-882707db888b?q=80&w=1080&auto=format&fit=crop',
      'description': 'One of the oldest Juniper forests on Earth and the historic wooden architecture of Quaid-e-Azam Residency.',
      'tags': ['Juniper Forest', 'Heritage', 'Chilly Breezes'],
    },
    {
      'id': '23',
      'name': 'Astola Island',
      'country': 'Pakistan',
      'rating': 4.9,
      'price': 58000,
      'duration': '4 Days',
      'distance': '350 km from Karachi',
      'region': 'south',
      'latitude': 25.1200,
      'longitude': 63.8500,
      'image': 'https://images.unsplash.com/photo-1518837695005-2083093ee35b?q=80&w=1080&auto=format&fit=crop',
      'description': 'Pakistan largest uninhabited island with turquoise water, sea caves, isolated shores, and coral beds.',
      'tags': ['Island Trek', 'Deep Sea', 'Turquoise Waters'],
    },
    {
      'id': '24',
      'name': 'Attabad Lake Gojal',
      'country': 'Pakistan',
      'rating': 4.9,
      'price': 39000,
      'duration': '4 Days',
      'distance': '620 km',
      'region': 'north',
      'latitude': 36.3333,
      'longitude': 74.8667,
      'image': 'https://images.unsplash.com/photo-1627894483216-2138af692e32?q=80&w=1080&auto=format&fit=crop',
      'description': 'Speedboat across turquoise alpine waters and cross the daring suspension bridges of upper Hunza.',
      'tags': ['Turquoise Lake', 'Boating', 'Bridges'],
    },
    {
      'id': '25',
      'name': 'Kalam Mahodand Lake',
      'country': 'Pakistan',
      'rating': 4.8,
      'price': 33000,
      'duration': '4 Days',
      'distance': '330 km',
      'region': 'north',
      'latitude': 35.4900,
      'longitude': 72.5800,
      'image': 'https://images.unsplash.com/photo-1668936782695-5f7657dc793d?q=80&w=1080&auto=format&fit=crop',
      'description': 'Traverse the wild Ushu pine forest and trout streams to reach the glacial jewel Mahodand Lake in upper Swat.',
      'tags': ['Swat Valley', 'Glacial Lake', 'Jeep Ride'],
    },
  ];

  static const List<Map<String, dynamic>> featuredPlaces = [
    {
      'id': 'f1',
      'name': 'Lahore',
      'country': 'Pakistan',
      'rating': 4.6,
      'price': 25000,
      'distance': '350 km',
      'region': 'central',
      'latitude': 31.5204,
      'longitude': 74.3587,
      'image': 'https://images.unsplash.com/photo-1622546758596-f1f06ba11f58?q=80&w=1080&auto=format&fit=crop',
      'description': 'The heart of Pakistan, famous for Minar-e-Pakistan, Badshahi Mosque, rich food, and culture.',
      'tags': ['Culture', 'Food', 'History'],
    },
    {
      'id': 'f2',
      'name': 'Islamabad',
      'country': 'Pakistan',
      'rating': 4.8,
      'price': 30000,
      'distance': '0 km',
      'region': 'central',
      'latitude': 33.6844,
      'longitude': 73.0479,
      'image': 'https://images.unsplash.com/photo-1608020932658-d0e19a69580b?q=80&w=1080&auto=format&fit=crop',
      'description': 'The capital city, featuring the iconic Faisal Mosque against the Margalla Hills.',
      'tags': ['City', 'Nature', 'Peaceful'],
    },
    {
      'id': 'f3',
      'name': 'Naran',
      'country': 'Pakistan',
      'rating': 4.7,
      'price': 40000,
      'distance': '280 km',
      'region': 'central',
      'latitude': 34.9085,
      'longitude': 73.6528,
      'image': 'https://images.unsplash.com/photo-1668061867899-02b4cfa34747?q=80&w=1080&auto=format&fit=crop',
      'description': 'A beautiful valley surrounded by lush green mountains and gateway to Saif-ul-Malook Lake.',
      'tags': ['Valley', 'Nature', 'River'],
    },
    {
      'id': 'f4',
      'name': 'Kund Malir',
      'country': 'Pakistan',
      'rating': 4.8,
      'price': 24000,
      'distance': '240 km',
      'region': 'south',
      'latitude': 25.5000,
      'longitude': 65.4500,
      'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1080&auto=format&fit=crop',
      'description': 'Pristine golden beach on the Arabian Sea framed by the desert mountains of Hingol.',
      'tags': ['Beach', 'Balochistan', 'Coastal'],
    },
    {
      'id': 'f5',
      'name': 'Kumrat Valley',
      'country': 'Pakistan',
      'rating': 4.8,
      'price': 34000,
      'distance': '370 km',
      'region': 'north',
      'latitude': 35.5414,
      'longitude': 72.2197,
      'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=1080&auto=format&fit=crop',
      'description': 'Alpine river streams and virgin deodar pine forests in Khyber Pakhtunkhwa.',
      'tags': ['Pine Trees', 'Rivers', 'Hiking'],
    },
  ];


  static const List<Map<String, dynamic>> chatMessages = [
    {
      'isMe': false,
      'text': 'Hi! I am your AI Travel Assistant. Where would you like to go?',
      'time': '10:00 AM',
    },
    {
      'isMe': true,
      'text': 'I am looking for a relaxing mountain vacation.',
      'time': '10:01 AM',
    },
    {
      'isMe': false,
      'text': 'Great! A scenic mountain getaway. Here are a few top recommendations for you:',
      'time': '10:02 AM',
      'destination_card': true, 
    },
    {
      'isMe': true,
      'text': 'Swat looks amazing! What is the estimated budget?',
      'time': '10:05 AM',
    },
    {
      'isMe': false,
      'text': 'For a 5-day trip to Swat for two, including travel, accommodation, and food, you are looking at approximately PKR 75,000.',
      'time': '10:06 AM',
    },
  ];

  static const List<Map<String, dynamic>> routeOptions = [
    {
      'id': 'fast',
      'title': 'Fastest Route (KKH Highway)',
      'duration': '11h 30m',
      'distance': '580 km',
      'stops': 1,
      'price': 'PKR 12,000',
      'type': 'fast',
      'tag': 'Fastest Path',
      'color': 0xFF0D9488,
    },
    {
      'id': 'scenic',
      'title': 'Scenic Route (Naran & Babusar Pass)',
      'duration': '14h 45m',
      'distance': '640 km',
      'stops': 5,
      'price': 'PKR 16,500',
      'type': 'scenic',
      'tag': 'Scenic Mountain Corridor',
      'color': 0xFFF59E0B,
    },
  ];

  static const List<Map<String, dynamic>> routeAttractions = [
    {
      'id': 'att_1',
      'name': 'Kallar Kahar Lake',
      'category': 'Lake',
      'latitude': 32.7819,
      'longitude': 72.7056,
      'description': 'Salt lake with natural gardens, historical Takht-e-Babri, and peacocks.',
      'image': 'https://images.unsplash.com/photo-1630139266136-1e663a0a322e?q=80&w=2074&auto=format&fit=crop',
      'rating': 4.5,
      'distance': '125 km from Islamabad',
    },
    {
      'id': 'att_2',
      'name': 'Saif-ul-Malook Lake',
      'category': 'Lake',
      'latitude': 34.8767,
      'longitude': 73.6931,
      'description': 'Legendary glacial lake surrounded by snow-draped Malika Parbat peak.',
      'image': 'https://images.unsplash.com/photo-1581895690858-a5ea6c4d7e00?q=80&w=2070&auto=format&fit=crop',
      'rating': 4.9,
      'distance': '285 km from Islamabad',
    },
    {
      'id': 'att_3',
      'name': 'Babusar Top Pass',
      'category': 'Mountain Pass',
      'latitude': 35.1481,
      'longitude': 74.0483,
      'description': 'High mountain pass at 4,173 meters with panoramic Himalayan and Karakoram vistas.',
      'image': 'https://images.unsplash.com/photo-1595166249673-c62d0943eb14?q=80&w=2070&auto=format&fit=crop',
      'rating': 4.8,
      'distance': '360 km from Islamabad',
    },
    {
      'id': 'att_4',
      'name': 'Lulusar Lake & Waterfall',
      'category': 'Waterfall & Lake',
      'latitude': 35.0833,
      'longitude': 73.9167,
      'description': 'Pristine mountain lake with cascading alpine runoff waterfalls.',
      'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=2070&auto=format&fit=crop',
      'rating': 4.7,
      'distance': '330 km from Islamabad',
    },
    {
      'id': 'att_5',
      'name': 'Altit Fort & Royal Garden',
      'category': 'Historic Heritage',
      'latitude': 36.3139,
      'longitude': 74.6714,
      'description': 'Ancient 900-year-old fort perched above the Hunza River canyon.',
      'image': 'https://images.unsplash.com/photo-1631558288597-28d8ed273fec?q=80&w=2070&auto=format&fit=crop',
      'rating': 4.9,
      'distance': 'Destination Landmark',
    },
    {
      'id': 'att_6',
      'name': 'Attabad Lake & Tunnel',
      'category': 'Scenic Landmark',
      'latitude': 36.3333,
      'longitude': 74.8667,
      'description': 'World-famous turquoise blue lake formed along the Karakoram Highway.',
      'image': 'https://images.unsplash.com/photo-1627894483216-2138af692e32?q=80&w=2070&auto=format&fit=crop',
      'rating': 4.9,
      'distance': '20 km past Hunza',
    },
  ];

  static const List<String> moods = [
    'Relaxing', 'Adventurous', 'Romantic', 'Cultural', 'Nature', 'Historical'
  ];
}
